//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentModel
    {
        public string CommentID { get; set; }
        public string Text { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Userid { get; set; }
    }
}
