//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class geekdaysEntities_new : DbContext
    {
        public geekdaysEntities_new()
            : base("name=geekdaysEntities_new")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CategoryModel> CategoryModels { get; set; }
        public virtual DbSet<CommentModel> CommentModels { get; set; }
        public virtual DbSet<LinkChatUser> LinkChatUsers { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<ResourceModel> ResourceModels { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
    }
}
