//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResourceModel()
        {
            this.Links = new HashSet<Link>();
        }
    
        public int ResourceId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string URL { get; set; }
        public string Disciption { get; set; }
        public string LinkToImg { get; set; }
        public double Score { get; set; }
        public Nullable<int> Category_CategoryID { get; set; }
    
        public virtual CategoryModel CategoryModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link> Links { get; set; }
    }
}
